export default {
  'zh-CN': {
    commons: {
      xiaoai: '小爱',
      admin: '管理员',
      editor: '赵晓编',
      quit: '退出',
      hi: '您好',
      index: '首页',
      userManage: '用户管理',
      share: '分享功能',
      infoManage: '信息管理',
      infoShow: '个人信息',
      infoShow1: '个人信息子菜单1',
      infoShow2: '个人信息子菜单2',
      infoShow3: '个人信息子菜单3',
      infoShow4: '个人信息子菜单4',
      infoShow5: '个人信息子菜单5',
      infoModify: '修改信息',
      infoModify1:'修改信息子菜单1',
      infoModify2:'修改信息子菜单2',
      infoModify3:'修改信息子菜单3',
      fundManage: '资金管理',
      fundList: '资金流水',
      chinaTabsList: '区域投资',
      fundData: '资金数据',
      fundPosition: '投资分布',
      typePosition: '项目分布',
      incomePayPosition: '收支分布',
      permission: '权限设置',
      pagePer: '页面权限',
      directivePer: '按钮权限',
      errorPage: '错误页面',
      page401:'401',
      page404:'404',
      wechatNumber: '微信号'
    },
    index:{
      yearLoss:'年度总盈亏',
      yearProfit:'年度收益率',
      potentialInvestor:'潜在投资人',
      intentionInvestor:'意向投资人',
      waitExamineInvestor:'待审投资人',
      examiningInvestor:'审核中投资人',
      tenMillion:'千万元',
      person:'人'
    }
  },
  'zh-TW': {
    commons: {
      xiaoai: '小愛',
      admin: '管理員',
      editor: '趙曉編',
      quit: '退出',
      hi: '您好',
      index: '首頁',
      userManage: '用戶管理',
      share: '分享功能',
      infoManage: '信息管理',
      infoShow: '個人信息',
      infoShow1: '個人信息子菜單1',
      infoShow2: '個人信息子菜單2',
      infoShow3: '個人信息子菜單3',
      infoShow4: '個人信息子菜單4',
      infoShow5: '個人信息子菜單5',
      infoModify: '修改信息',
      infoModify1:'修改信息子菜單1',
      infoModify2:'修改信息子菜單2',
      infoModify3:'修改信息子菜單3',
      fundManage: '資金管理',
      fundList: '資金流水',
      chinaTabsList: '區域投資',
      fundData: '資金數據',
      fundPosition: '投資分布',
      typePosition: '項目分布',
      incomePayPosition: '收支分布',
      permission: '權限設置',
      pagePer: '頁面權限',
      directivePer: '按鈕權限',
      errorPage: '錯誤頁面',
      page401:'401',
      page404:'404',
      wechatNumber: '微信號'
    },
    index:{
      yearLoss:'年度總盈虧',
      yearProfit:'年度收益率',
      potentialInvestor:'潛在投資人',
      intentionInvestor:'意向投資人',
      waitExamineInvestor:'待審投資人',
      examiningInvestor:'審核中投資人',
      tenMillion:'千萬元',
      person:'人'
    }
  },
  'zh-EN': {
    commons: {
      xiaoai: 'Ai.',
      admin: 'Admin',
      editor: 'Editor',
      quit: 'Sign Out',
      hi: 'Hi',
      index: 'Dashboard',
      userManage: 'Users',
      share: 'Share',
      infoManage: 'Infos',
      infoShow: 'InfoShow',
      infoShow1: 'InfoShow1',
      infoShow2: 'InfoShow2',
      infoShow3: 'InfoShow3',
      infoShow4: 'InfoShow4',
      infoShow5: 'InfoShow5',
      infoModify: 'InfoModify',
      infoModify1:'InfoModify1',
      infoModify2:'InfoModify2',
      infoModify3:'InfoModify3',
      fundManage: 'Money',
      fundList: 'MoneyList',
      chinaTabsList: 'AreaList',
      fundData: 'FundData',
      fundPosition: 'FundPosition',
      typePosition: 'TypePosition',
      incomePayPosition: 'IncomePayPosition',
      permission: 'Permission',
      pagePer: 'PagePermission',
      directivePer: 'DirectivePermission',
      errorPage: 'ErrorPage',
      page401:'401',
      page404:'404',
      wechatNumber: 'wechat'
    },
    index:{
      yearLoss:'Year Loss',
      yearProfit:'Year Profit',
      potentialInvestor:'Potential Investor',
      intentionInvestor:'Intention Investor',
      waitExamineInvestor:'Wait Examine Investor',
      examiningInvestor:'Examining Investor',
      tenMillion:'Ten Million',
      person:'P'
    }
  }
}
